on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # with:
        #   ref: master
        #   fetch-depth: 0   # ensures full history for commits

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run compile script
        run: node scripts/compile-recipes.js

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add recipes.json
          git add recipes.yaml
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: refresh recipes"
            # git push origin HEAD:${{ github.ref_name }}
            git push
          fi
